services:
  backend:
    build: Dindin.API/Dindin.API
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "./Dindin.API/Dindin.API:/src"
    command:
      - "dotnet"
      - "watch"
      - "run"
    depends_on:
      database:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    
  frontend:
    build: Dindin.React/vite-project
    ports:
      - "5173:5173"
    volumes:
      - "./DinDin.React/vite-project:/app"
      - /app/node_modules
    command:
      - "npm"
      - "run"
      - "dev"
      - "--"
      - "--host"

  database:
    image: postgres:18
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - polls_pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10

volumes:
  polls_pg_data:
